"""added password field

Revision ID: 21057ac16e52
Revises: c9cdc948567a
Create Date: 2022-05-02 00:48:34.221390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21057ac16e52'
down_revision = 'c9cdc948567a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
