"""added password field

Revision ID: 79189bd49287
Revises: 21057ac16e52
Create Date: 2022-05-02 03:17:19.760098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79189bd49287'
down_revision = '21057ac16e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.drop_column('users', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date', mysql.DATETIME(), nullable=False))
    op.drop_column('users', 'date_added')
    # ### end Alembic commands ###
