"""Initial Migration

Revision ID: c9cdc948567a
Revises: 
Create Date: 2022-04-27 01:08:26.290260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9cdc948567a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.String(length=200), nullable=True))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###
